-- Test data for PostgreSQL-to-PostgreSQL migration CI test
-- Exercises various PostgreSQL types and features

-- Idempotent: drop tables if they exist for re-runs
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS enum_test CASCADE;
DROP TABLE IF EXISTS json_data CASCADE;
DROP TABLE IF EXISTS basic_types CASCADE;
DROP TABLE IF EXISTS "Test""Tbl" CASCADE;
DROP TABLE IF EXISTS "test Tbl" CASCADE;
DROP TYPE IF EXISTS mood CASCADE;

-- Basic types table
CREATE TABLE basic_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT true,
    price NUMERIC(10,2),
    rating FLOAT DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO basic_types (name, description, active, price, rating) VALUES
    ('Widget A', 'A basic widget', true, 19.99, 4.5),
    ('Widget B', 'Another widget', false, 29.99, 3.8),
    ('Widget C', 'Premium widget', true, 49.99, 4.9);

-- JSONB table
CREATE TABLE json_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data JSONB NOT NULL,
    tags TEXT[]
);

INSERT INTO json_data (data, tags) VALUES
    ('{"key": "value", "count": 42}', ARRAY['test', 'json']),
    ('{"items": [1,2,3], "nested": {"a": 1}}', ARRAY['nested']);

-- Enum type
CREATE TYPE mood AS ENUM ('happy', 'sad', 'neutral');
CREATE TABLE enum_test (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    current_mood mood DEFAULT 'happy',
    score INTEGER CHECK (score >= 0 AND score <= 100)
);

INSERT INTO enum_test (current_mood, score) VALUES
    ('happy', 100),
    ('sad', 42),
    ('neutral', 75);

-- Table with foreign key
CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER REFERENCES basic_types(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    order_date DATE DEFAULT CURRENT_DATE
);

INSERT INTO orders (product_id, quantity) VALUES
    (1, 2),
    (2, 1),
    (1, 5);

-- Indexed table
CREATE TABLE logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event TEXT NOT NULL,
    severity INTEGER DEFAULT 0,
    logged_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_logs_severity ON logs(severity);
CREATE INDEX idx_logs_logged_at ON logs(logged_at);

INSERT INTO logs (event, severity) VALUES
    ('startup', 0),
    ('user login', 1),
    ('error: disk full', 5),
    ('shutdown', 0);

-- Money type
CREATE TABLE payments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount MONEY NOT NULL,
    paid_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO payments (amount) VALUES
    ('$100.00'),
    ('$250.50'),
    ('$999.99');

-- Special table names: mixed case, double quote, space
CREATE TABLE "Test""Tbl" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    val TEXT
);

INSERT INTO "Test""Tbl" (val) VALUES ('quote_test'), ('mixed_case');

CREATE TABLE "test Tbl" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    val TEXT
);

INSERT INTO "test Tbl" (val) VALUES ('space_test'), ('in_name');
