package pgsql

import (
	"context"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/tking320/pgloader-go/internal/catalog"
)

// ---------------------------------------------------------------------------
// Columns
// ---------------------------------------------------------------------------

func (s *PgSQLSource) fetchTableColumns(ctx context.Context, conn *pgxpool.Conn, tableOID uint32) ([]*catalog.Column, error) {
	// Get PK columns first (separate query to avoid "conn busy")
	pkCols, err := s.fetchPKColumns(ctx, conn, tableOID)
	if err != nil {
		return nil, err
	}
	pkSet := make(map[string]bool)
	for _, pk := range pkCols {
		pkSet[pk] = true
	}

	rows, err := conn.Query(ctx, `
		SELECT a.attname,
		       pg_catalog.format_type(a.atttypid, a.atttypmod) AS full_type,
		       a.attnotnull,
		       pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
		       a.attidentity::text,
		       COALESCE(d.description, '')
		FROM pg_catalog.pg_attribute a
		LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
		LEFT JOIN pg_catalog.pg_description d ON d.objoid = a.attrelid AND d.objsubid = a.attnum
		WHERE a.attrelid = $1
		  AND a.attnum > 0
		  AND NOT a.attisdropped
		ORDER BY a.attnum
	`, tableOID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var columns []*catalog.Column
	for rows.Next() {
		var name, fullType string
		var notNull bool
		var defaultExpr, attIdentity, comment *string
		if err := rows.Scan(&name, &fullType, &notNull, &defaultExpr, &attIdentity, &comment); err != nil {
			return nil, err
		}

		col := &catalog.Column{
			Name:       name,
			SourceType: fullType,
			IsPK:       pkSet[name],
		}

		col.TypeName = fullType
		col.TypeMod = ""

		if idx := strings.IndexByte(fullType, '('); idx > 0 {
			col.TypeName = fullType[:idx]
			col.TypeMod = fullType[idx:]
		}

		if notNull {
			col.Nullable = false
		} else {
			col.Nullable = true
		}

		if defaultExpr != nil && *defaultExpr != "" {
			col.Default = *defaultExpr
		}

		if attIdentity != nil && *attIdentity != "" {
			col.IsAutoInc = true
			if *attIdentity == "a" {
				col.ExtraDDL = "GENERATED ALWAYS AS IDENTITY"
			} else if *attIdentity == "d" {
				col.ExtraDDL = "GENERATED BY DEFAULT AS IDENTITY"
			}
		} else if strings.Contains(col.Default, "nextval(") {
			col.IsAutoInc = true
		}

		if comment != nil {
			col.Comment = *comment
		}

		// Apply CAST rules
		if s.castEngine != nil {
			baseType := parseBaseType(fullType)
			result := s.castEngine.Apply(baseType, fullType, col.Extra)
			col.TypeName = result.TargetType
			if result.DropTypemod {
				col.TypeMod = ""
			}
			col.Transform = result.Transform
		}

		columns = append(columns, col)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return columns, nil
}

func (s *PgSQLSource) fetchPKColumns(ctx context.Context, conn *pgxpool.Conn, tableOID uint32) ([]string, error) {
	rows, err := conn.Query(ctx, `
		SELECT a.attname
		FROM pg_catalog.pg_index i
		JOIN pg_catalog.pg_attribute a ON a.attrelid = i.indrelid
		     AND a.attnum = ANY(i.indkey)
		WHERE i.indrelid = $1 AND i.indisprimary
		  AND a.attnum > 0 AND NOT a.attisdropped
		ORDER BY a.attnum
	`, tableOID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var cols []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

// fetchSequenceNames resolves sequence names for auto-increment columns.
func (s *PgSQLSource) fetchSequenceNames(ctx context.Context, conn *pgxpool.Conn, t *catalog.Table) error {
	for _, col := range t.Columns {
		if col.IsAutoInc {
			row := conn.QueryRow(ctx, `
				SELECT pg_catalog.pg_get_serial_sequence($1, $2)
			`, t.QualifiedName(), col.Name)
			var seqName *string
			if err := row.Scan(&seqName); err == nil && seqName != nil {
				// pg_get_serial_sequence returns "schema.seqname" — strip schema prefix
				if parts := strings.Split(*seqName, "."); len(parts) > 1 {
					col.SequenceName = parts[len(parts)-1]
				} else {
					col.SequenceName = *seqName
				}
			}
		}
	}
	return nil
}

// parseBaseType extracts the base type name from a PostgreSQL format_type output.
func parseBaseType(fullType string) string {
	if idx := strings.IndexByte(fullType, '('); idx > 0 {
		return strings.TrimSpace(fullType[:idx])
	}
	return fullType
}
